2025-02-09 04:08:22,205 ERROR: An error occurred in home route: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. [in d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py:32]
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 29, in home
    return render_template("home.html", posts=posts)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
    ...<3 lines>...
    )
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-02-09 04:08:22,226 ERROR: An error occurred in home route: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. [in d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py:32]
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 29, in home
    return render_template("home.html", posts=posts)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
    ...<3 lines>...
    )
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-02-09 04:08:22,256 ERROR: An error occurred in home route: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. [in d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py:32]
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 29, in home
    return render_template("home.html", posts=posts)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
    ...<3 lines>...
    )
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-02-09 04:08:22,281 ERROR: An error occurred in home route: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. [in d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py:32]
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 29, in home
    return render_template("home.html", posts=posts)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
    ...<3 lines>...
    )
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2025-02-09 04:08:22,331 ERROR: An error occurred in home route: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info. [in d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py:32]
Traceback (most recent call last):
  File "d:\old laptop\2024\FURTHER UPGRADE\cs50_final_project\app\routes.py", line 29, in home
    return render_template("home.html", posts=posts)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 127, in _render
    app.update_template_context(context)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 530, in update_template_context
    context.update(self.ensure_sync(func)())
                   ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\noors\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask_login\login_manager.py", line 347, in _load_user
    raise Exception(
    ...<3 lines>...
    )
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
